language: python

python:
  - 3.7
  - 3.6

script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

  - flake8 .
  - black --check .
  - pytest
  - coverage xml -o coverage.xml

after_success:
  - codecov -t 1b952448-6bf8-4ecc-b990-8fa4a1ded9ed
